# Generated by Django 5.1.7 on 2025-06-17 18:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=100, verbose_name='Имя мастера')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия мастера')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/masters/', verbose_name='Фото мастера')),
                ('phone', models.CharField(db_index=True, max_length=20, verbose_name='Телефон мастера')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес мастера')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email мастера')),
                ('experience', models.PositiveIntegerField(verbose_name='Опыт работы (лет)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Мастера',
                'ordering': ['experience'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название услуги')),
                ('description', models.TextField(verbose_name='Описание услуги')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена услуги')),
                ('duration', models.PositiveIntegerField(blank=True, default=20, help_text='Время в минутах', verbose_name='Время выполнения услуги')),
                ('is_popular', models.BooleanField(blank=True, default=False, verbose_name='Популярная услуга')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/services/', verbose_name='Изображение услуги')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/reviews/', verbose_name='Фотография')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.master', verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='master',
            name='services',
            field=models.ManyToManyField(related_name='masters', to='core.service', verbose_name='Услуги мастера'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(db_index=True, max_length=100, verbose_name='Имя клиента')),
                ('phone', models.CharField(db_index=True, max_length=20, verbose_name='Телефон клиента')),
                ('comment', models.TextField(blank=True, db_index=True, verbose_name='Комментарий клиента')),
                ('status', models.CharField(choices=[('not_approved', 'Не подтвержден'), ('moderated', 'Прошел модерацию'), ('spam', 'Спам'), ('approved', 'Подтвержден'), ('in_awaiting', 'В ожидании'), ('completed', 'Завершен'), ('canceled', 'Отменен')], default='not_approved', max_length=50, verbose_name='Статус заказа')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('appointment_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата записи')),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.master', verbose_name='Мастер')),
                ('services', models.ManyToManyField(blank=True, related_name='orders', to='core.service', verbose_name='Услуги')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-date_created'],
                'indexes': [models.Index(fields=['status'], name='status_idx'), models.Index(fields=['date_created'], name='created_at_idx'), models.Index(fields=['client_name', 'phone', 'comment'], name='client_phone_comment_idx')],
            },
        ),
    ]
