# Generated by Django 5.1.7 on 2025-04-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('services', models.CharField(max_length=200)),
                ('master_id', models.IntegerField()),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
