# Generated by Django 5.1.7 on 2025-04-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('phone', models.CharField(default='', max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('not_approved', 'Не подтвержден'), ('moderated', 'Прошел модерацию'), ('spam', 'Спам'), ('approved', 'Подтвержден'), ('in_awaiting', 'В ожидании'), ('completed', 'Завершен'), ('canceled', 'Отменен')], default='not_approved', max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('appointment_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
