# Generated by Django 5.1.7 on 2025-04-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_master_first_name_alter_master_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество просмотров'),
        ),
    ]
