# Generated by Django 5.1.7 on 2025-04-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_master_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.PositiveIntegerField(default=20, help_text='Время в минутах', verbose_name='Время выполнения услуги'),
        ),
    ]
