# Generated by Django 5.1.7 on 2025-05-27 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='master',
            options={'ordering': ['experience'], 'verbose_name': 'Мастер', 'verbose_name_plural': 'Мастера'},
        ),
        migrations.AlterField(
            model_name='master',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адрес мастера'),
        ),
        migrations.AlterField(
            model_name='master',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email мастера'),
        ),
        migrations.AlterField(
            model_name='master',
            name='experience',
            field=models.PositiveIntegerField(verbose_name='Опыт работы (лет)'),
        ),
        migrations.AlterField(
            model_name='master',
            name='first_name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Имя мастера'),
        ),
        migrations.AlterField(
            model_name='master',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='master',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Фамилия мастера'),
        ),
        migrations.AlterField(
            model_name='master',
            name='phone',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Телефон мастера'),
        ),
        migrations.AlterField(
            model_name='master',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/masters/', verbose_name='Фото мастера'),
        ),
        migrations.AlterField(
            model_name='master',
            name='services',
            field=models.ManyToManyField(related_name='masters', to='core.service', verbose_name='Услуги мастера'),
        ),
        migrations.AlterField(
            model_name='order',
            name='appointment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата записи'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Имя клиента'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, db_index=True, verbose_name='Комментарий клиента'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='order',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.master', verbose_name='Мастер'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Телефон клиента'),
        ),
        migrations.AlterField(
            model_name='order',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='orders', to='core.service', verbose_name='Услуги'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('not_approved', 'Не подтвержден'), ('moderated', 'Прошел модерацию'), ('spam', 'Спам'), ('approved', 'Подтвержден'), ('in_awaiting', 'В ожидании'), ('completed', 'Завершен'), ('canceled', 'Отменен')], default='not_approved', max_length=50, verbose_name='Статус заказа'),
        ),
    ]
