# Generated by Django 5.1.7 on 2025-06-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='html_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание (HTML)'),
        ),
        migrations.AddField(
            model_name='post',
            name='md_description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
    ]
