# Название нашего workflow для отображения в интерфейсе GitHub
name: Deploy to VPS

# Указываем когда запускать - при push в main ветку
on:
  push:
    branches: [ main ]

# Определяем задачи для выполнения 
jobs:
  deploy:
    # Указываем на какой ОС запускать
    runs-on: ubuntu-latest
    
    steps:
      # Получаем код из репозитория
      - uses: actions/checkout@v3

      # Деплоим на сервер через SSH
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          # Используем секреты из GitHub для подключения
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          
          # Команды выполняемые на сервере
          script: |
            # Переходим в директорию проекта
            cd /home/v/django_consult_412

            # Останавливаем службу приложения  (с sudo и передачей пароля)
            echo "${{ secrets.PASSWORD }}" | sudo -S systemctl stop gunicorn_django_consult
            
            # Обновляем код из репозитория (с sudo и передачей пароля)
            echo "${{ secrets.PASSWORD }}" | git pull
            
            # Если у вас PIP
            # Активируем виртуальное окружение
            # source venv/bin/activate
            
            # Обновляем зависимости
            # pip install -r requirements.txt

            # Если у вас Poetry
            poetry install --no-root 
            
            # Создаем файл .env из секрета где записано все его содержимое
            echo "${{ secrets.ENV_FILE }}" > .env

            # Собираем статику 
            poetry run python manage.py collectstatic --noinput
            
            # Перезапускаем systemd сервис (с sudo и передачей пароля)
            echo "${{ secrets.PASSWORD }}" | sudo -S systemctl start gunicorn_django_consult